name: Build dart_simple_live

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 克隆代码到 GitHub Actions 环境
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 Flutter SDK（指定版本）
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"  # 根据项目需求调整版本

      # 3. 切换到 Flutter 项目子模块（simple_live_app）
      - name: Change to Flutter project directory
        run: |
          cd simple_live_app || { echo "Directory not found"; exit 1; }

      # 4. 安装依赖（flutter pub get）
      - name: Get dependencies
        run: |
          flutter pub get

      # 5. 构建 Android APK 和 App Bundle
      - name: Build Android App
        run: |
          flutter build apk --release
          flutter build appbundle --release

      # 6. 上传构建产物
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
