name: Dart自动编译

on:
  push:
    branches: [main]  # 触发条件：main分支有推送时执行

jobs:
  build:
    name: Dart编译任务
    runs-on: ubuntu-latest  # 使用最新Ubuntu环境
    container:
      image: google/dart:latest  # 使用官方Dart镜像[1](@ref)steps:
      - name: 检出代码
        uses: actions/checkout@v4  # 拉取最新代码[2](@ref)
      
      - name: 安装依赖
        run: dart pub get  # 获取pubspec.yaml依赖
      
      - name: 执行编译
        run: dart build  # 执行编译命令
      
      - name: 上传编译产物
        uses: actions/upload-artifact@v4  # 保存编译结果
        with:
          name: dart_build_output
          path: build/  # 根据实际编译输出路径调整
