name: Build dart_simple_live

on:
  push:
    branches:
      - master  # 监听 master 分支的推送事件
  pull_request:
    branches:
      - master  # 监听 master 分支的 Pull Request 事件

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 克隆代码到运行环境

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0  # 根据项目要求设置 Flutter 版本

      - name: Get dependencies
        run: flutter pub get  # 安装依赖

      - name: Build Android App
        run: |
          flutter build apk --release  # 构建 Android APK
          flutter build appbundle --release  # 构建 Android App Bundle

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
